insert into Positions values ('Профессор')
insert into Positions values ('Доцент')
insert into Positions values ('Старший преподаватель')
insert into Positions values ('Аспирант')
insert into Positions values ('Ассистент')

insert into Disciplines values ('Базы Данных')
insert into Disciplines values ('Программирование')
insert into Disciplines values ('Методы оптимизации')
insert into Disciplines values ('ТОАУ')
insert into Disciplines values ('Разработка мобильных приложений')
insert into Disciplines values ('Web-Приложения')
insert into Disciplines values ('Объектно-ориентированное программирование')
insert into Disciplines values ('Системы и сети массового обслуживания')
insert into Disciplines values ('Операционные системы')
insert into Disciplines values ('Параллельное программирование')
insert into Disciplines values ('IP-телефония и телевидение')
insert into Disciplines values ('Вычислительные системы')
insert into Disciplines values ('Сетевая безопасность')
insert into Disciplines values ('Моделирование информационно-вычислительных систем')

insert into Teachers values ('Чигарина','Елена','Ивановна',1,2)
insert into Teachers values ('Головнин','Олег','Константинович',1,2)
insert into Teachers values ('Востокин','Сергей','Владимирович',1,1)
insert into Teachers values ('Прохоров','Сергей','Антонович',1,1)
insert into Teachers values ('Михеева','Татьяна','Ивановна',1,1)
insert into Teachers values ('Сухов','Андрей','Михайлович',1,1)
insert into Teachers values ('Есипов','Борис','Алексеевич',1,2)
insert into Teachers values ('Лёзин','Илья','Александрович',1,2)
insert into Teachers values ('Лёзина','Ирина','Викторовна',1,2)
insert into Teachers values ('Литвинов','Владимир','Геннадьевич',1,2)
insert into Teachers values ('Симонова','Елена','Витальевна',1,2)

insert into Specialities values ('Информатика и вычислительная техника (а)')
insert into Specialities values ('Информатика и вычислительная техника (п)')
insert into Specialities values ('Фундаментальная информатика и информационные технологии')
insert into Specialities values ('Прикладная математика и информатика')

insert into StudyGroup values (1,'Осенний',6)
insert into StudyGroup values (1,'Осенний',7)
insert into StudyGroup values (1,'Осенний',8)
insert into StudyGroup values (1,'Осенний',9)